name: Build Chrome Extension
on: [workflow_dispatch]
jobs:
  build:
    name: build-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: Borales/actions-yarn@2.3.0
        with:
          cmd: install
      - uses: Borales/actions-yarn@2.3.0
        with:
          cmd: lint
      - uses: Borales/actions-yarn@2.3.0
        with:
          cmd: build
      - uses: papeloto/action-zip@v1
        with:
          files: dist/
          dest: extension.zip
      - uses: actions/upload-artifact@latest
        with:
          name: extension
          path: ${{ github.workspace }}/extension.zip
      # - uses: Klemensas/chrome-extension-upload-action@latest
      #   with:
      #     refresh-token:
      #     client-id:
      #     client-secret:
      #     file-name: ./extension.zip
      #     app-id:
      #     publish: true
